WITH MAX_DATE_BY_DISTRICT AS (
    SELECT
        DISTRICT,
        MAX(META_DATE) AS META_DATE
    FROM TRANSFORM_DEV.DBT_IROSE.STG_STATION_META
    GROUP BY DISTRICT

),

MOST_RECENT_STATION_META AS (
    SELECT
        ANY_VALUE(ID) OVER (PARTITION BY ID ORDER BY META_DATE) AS ID,
        ANY_VALUE(DISTRICT) OVER (PARTITION BY ID ORDER BY META_DATE) AS DISTRICT,
        MIN(META_DATE) OVER (PARTITION BY ID ORDER BY META_DATE) AS START_DATE,
        MAX(META_DATE) OVER (PARTITION BY ID ORDER BY META_DATE) AS END_DATE
    FROM TRANSFORM_DEV.DBT_IROSE.STG_STATION_META
),

MOST_RECENT_STATION_META_2 AS (
    SELECT
        * EXCLUDE END_DATE,
        IFF(
            END_DATE = (
                SELECT M.META_DATE
                FROM MAX_DATE_BY_DISTRICT AS M
                WHERE M.DISTRICT = S.DISTRICT
            ),
            NULL,
            END_DATE
        ) AS END_DATE
    FROM MOST_RECENT_STATION_META AS S
)

SELECT * FROM MOST_RECENT_STATION_META_2
