{% set district_re='clhouse/meta/d(\\\\d{2})' %}

SELECT
    SUBSTR(FILENAME, 14, 2)::INT AS DISTRICT,
    ID,
    SAMPLE_DATE,
    SAMPLE_TIMESTAMP,
    FLOW_1,
    OCCUPANCY_1,
    SPEED_1,
    FLOW_2,
    OCCUPANCY_2,
    SPEED_2,
    FLOW_3,
    OCCUPANCY_3,
    SPEED_3,
    FLOW_4,
    OCCUPANCY_4,
    SPEED_4,
    FLOW_5,
    OCCUPANCY_5,
    SPEED_5,
    FLOW_6,
    OCCUPANCY_6,
    SPEED_6,
    FLOW_7,
    OCCUPANCY_7,
    SPEED_7,
    FLOW_8,
    OCCUPANCY_8,
    SPEED_8
FROM {{ source('clearinghouse', 'station_raw') }}
