config:
  send_anonymous_usage_stats: false
  use_colors: true
  warn_error: true

caltrans_pems:
  target: dev
  outputs:
    dev:
      type: snowflake

      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: READER_DEV
      warehouse: REPORTING_XS_DEV
      database: ANALYTICS_DEV
      schema: ci_should_not_create_this_schema
      threads: 4
    prd:
      type: snowflake

      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: READER_PRD
      warehouse: REPORTING_XS_PRD
      database: ANALYTICS_PRD
      schema: ANALYTICS
      threads: 4
